#' Computes short cut for testing intersection hypotheses of m hypotheses
#'
#' @param p vector of p-values
#' @param method either "Stouffer" or "Fisher" combination test
#' @param Gnull list of null distribution, generated by create.null
#' @param func userdefined function. Is set to zero if no user defined function is given
#' @param alp significance level
#' @returns adjusted p-values
#' @export
#'

cons.test = function(p,method="stouffer",Gnull,alp,func=NULL)#=FALSE,alp,func=NULL,runs=10^5,eps=10^(-10))
{
  # if (Gnull==FALSE)
  #  Gnull<-create.null(method=method,alp=alp,h=h,runs=10^5,eps=10^(-10),func=func)

  m = length(p)
  p_adj = numeric(m)
  order_raw=order(p)
  for (i in 1:m) {
    sorted_p <- p[order_raw]
    ith_smallest <- sorted_p[i]
    # Get indices of all elements larger or equal to the i-th smallest element
    indices <- which(p >= ith_smallest)
    p_adj[i] = pint(p[indices],method,Gnull,alp,func) #brauch hier #G; Sollte ich vorher berechnen.
    if (i > 1) {
      p_adj[i] = max(p_adj[i], p_adj[i - 1])
    }
  }
  return(p_adj[order(order_raw)])
}

