#' Computes a consonant test (p-value) for a specific intersection hypothesis iteratively
#'
#' @param p vector of p-values
#' @param method either "Stouffer" or "Fisher" combination test
#' @param Gnull list of null distribution, generated by create.null
#' @param func userdefined function. Is set to zero if no user defined function is given
#' @param alp significance level
#' @returns consonant p-value
#' @export
#'

pint<-function(p,method="stouffer",Gnull,alp,func=NULL)
{
  p_sort=sort(p)
  l=length(p)
  L=1:l
  h=l
  K=L[1]
  pK=list(p_sort[1])
  while(h>=2)
  {
    K=c(K,L[h])
    k=length(K)
    ps=p_sort[K]
    TK=fk(ps,method,func) # use here the combination function. #TK is test statistic
    if(pK[[k-1]]>alp) TK=0
    pK[[k]]=Gnull[[k]](TK)
    h=h-1
  }
  return(unlist(pK[l]))
}
